server {
    listen 80;
    server_name _;
    client_max_body_size 2m;

    root /var/www/html/public;
    index index.php;

    location = /up {
        try_files $uri /index.php?$query_string;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /index.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param HTTP_HOST $http_host;
        fastcgi_pass app:9000;
    }

    location ~ \.php$ {
        return 404;
    }

    location ~ /\. {
        deny all;
    }
}
